//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// GNPDF_res.rc

#define IDC_MENU_OPEN                       100
#define IDC_MENU_DELETE                     101
#define IDC_MENU_PROP                       102

#define IDS_APPNAME                         100
#define IDS_NOSPEC                          101
#define IDS_PORTRAIT                        102
#define IDS_LANDSCAPE                       103
#define IDS_PICTITLE_01                     110
#define IDS_PICTITLE_02                     111
#define IDS_PICTITLE_03                     112
#define IDS_PICTITLE_04                     113
#define IDS_PICTITLE_05                     114
#define IDS_PICTITLE_06                     115
#define IDS_PICTITLE_07                     117
#define IDS_FONT_01                         118
#define IDS_FONT_02                         119
#define IDS_FONT_03                         120
#define IDS_FONT_04                         121
#define IDS_OUTPUT_01                       128
#define IDS_OUTPUT_02                       129
#define IDS_OUTPUT_03                       130
#define IDS_OUTPUT_04                       131
#define IDS_OUTPUT_05                       133
#define IDS_OUTPUT_06                       134
#define IDS_OUTPUT_07                       135
#define IDS_OUTPUT_08                       136
#define IDS_INVALIDSTRING                   137
#define IDS_OPENFILTER                      138
#define IDS_ADDPICTURE                      139
#define IDS_64KB                            140
#define IDS_128KB                           141
#define IDS_256KB                           142
#define IDS_512KB                           143
#define IDS_1MB                             144
#define IDS_2MB                             145
#define IDS_A3                              146
#define IDS_A4                              147
#define IDS_A5                              148
#define IDS_B4                              149
#define IDS_B5                              150
#define IDS_TEXTTOOLONG                     151
#define IDS_YES                             152
#define IDS_NO                              153
#define IDS_NOLIMIT                         154
#define IDS_LISTISEMPTY                     155
#define IDS_TAG_FILENAME                    156
#define IDS_TAG_SHORTNAME                   157
#define IDS_TAG_IMAGENO                     158
#define IDS_TAG_IMAGETOTAL                  159
#define IDS_TAG_PAGENO                      160
#define IDS_TAG_PAGETOTAL                   161
#define IDS_TAG_DATE                        162
#define IDS_TAG_TIME                        163
#define IDS_TAG_DATETIME                    164
#define IDS_TAG_NOW                         165
#define IDS_TAG_DATE_SHOOT                  166
#define IDS_TAG_TIME_SHOOT                  167
#define IDS_TAG_DATETIME_SHOOT              168
#define IDS_TAG_DATE_MODIFIED               169
#define IDS_TAG_TIME_MODIFIED               170
#define IDS_TAG_DATETIME_MODIFIED           171
#define IDS_TAG_WIDTH                       172
#define IDS_TAG_HEIGHT                      173
#define IDS_TAG_FILESIZE                    174
#define IDS_TAG_PATHNAME                    175
#define IDS_TAG_TODAY                       176
#define IDS_TAG_YEAR                        177
#define IDS_TAG_MONTH                       178
#define IDS_TAG_DAY                         179
#define IDS_DATEFORMAT                      180
#define IDS_TIMEFORMAT                      181
#define IDS_COPYFILEFAILED                  182
#define IDS_SUCCEEDED                       183
#define IDS_PROCESSINGNOW                   184
#define IDS_GENERATE                        185
#define IDS_PAGENUMBER                      186
#define IDS_FIELD_MARGIN                    187
#define IDS_FIELD_ROWS                      188
#define IDS_FIELD_COLUMNS                   189
#define IDS_FIELD_FONT_SIZE                 190
#define IDS_FIELD_OUTPUT_NAME               191
#define IDS_REASON_ZERO_OR_MORE_REAL        192
#define IDS_REASON_POSITIVE_INTEGER         193
#define IDS_REASON_POSITIVE_REAL            194
#define IDS_REASON_NON_EMPTY_STRING         195
#define IDS_SUSIE_IMAGES                    196
#define IDS_HEADER_01                       197
#define IDS_HEADER_02                       198
#define IDS_HEADER_03                       199
#define IDS_FOOTER_01                       200
#define IDS_FOOTER_02                       201
#define IDS_FOOTER_03                       202
#define IDS_LOGO                            203

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
