//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// GazoNarabe_res.rc

#define IDS_APPNAME                         100
#define IDS_NOSPEC                          101
#define IDS_PORTRAIT                        102
#define IDS_LANDSCAPE                       103
#define IDS_PICTITLE_01                     110
#define IDS_PICTITLE_02                     111
#define IDS_PICTITLE_03                     112
#define IDS_PICTITLE_04                     113
#define IDS_PICTITLE_05                     114
#define IDS_PICTITLE_06                     115
#define IDS_PICTITLE_07                     117
#define IDS_FONT_01                         118
#define IDS_FONT_02                         119
#define IDS_FONT_03                         120
#define IDS_FONT_04                         121
#define IDS_OUTPUT_01                       128
#define IDS_OUTPUT_02                       129
#define IDS_OUTPUT_03                       130
#define IDS_OUTPUT_04                       131
#define IDS_OUTPUT_05                       133
#define IDS_OUTPUT_06                       134
#define IDS_INVALIDSTRING                   135
#define IDS_FILTER                          136
#define IDS_ADDPICTURE                      137
#define IDS_64KB                            138
#define IDS_128KB                           139
#define IDS_256KB                           140
#define IDS_512KB                           141
#define IDS_1MB                             142
#define IDS_2MB                             143
#define IDS_A3                              144
#define IDS_A4                              145
#define IDS_A5                              146
#define IDS_B4                              147
#define IDS_B5                              148
#define IDS_TEXTTOOLONG                     149
#define IDS_YES                             150
#define IDS_NO                              151
#define IDS_NOLIMIT                         152
#define IDS_LISTISEMPTY                     153
#define IDS_TAG_FILENAME                    154
#define IDS_TAG_SHORTNAME                   155
#define IDS_TAG_IMAGENO                     156
#define IDS_TAG_IMAGETOTAL                  157
#define IDS_TAG_PAGENO                      158
#define IDS_TAG_PAGETOTAL                   159
#define IDS_TAG_DATE                        160
#define IDS_TAG_TIME                        161
#define IDS_TAG_DATETIME                    162
#define IDS_TAG_NOW                         163
#define IDS_TAG_DATE_SHOOT                  164
#define IDS_TAG_TIME_SHOOT                  165
#define IDS_TAG_DATETIME_SHOOT              166
#define IDS_TAG_DATE_MODIFIED               167
#define IDS_TAG_TIME_MODIFIED               168
#define IDS_TAG_DATETIME_MODIFIED           169
#define IDS_TAG_WIDTH                       170
#define IDS_TAG_HEIGHT                      171
#define IDS_TAG_FILESIZE                    172
#define IDS_TAG_PATHNAME                    173
#define IDS_TAG_TODAY                       174
#define IDS_TAG_YEAR                        175
#define IDS_TAG_MONTH                       176
#define IDS_TAG_DAY                         177
#define IDS_DATEFORMAT                      178
#define IDS_TIMEFORMAT                      179
#define IDS_COPYFILEFAILED                  180
#define IDS_SUCCEEDED                       181
#define IDS_PROCESSINGNOW                   182
#define IDS_GENERATE                        183
#define IDS_PAGENUMBER                      184
#define IDS_FIELD_MARGIN                    185
#define IDS_FIELD_ROWS                      186
#define IDS_FIELD_COLUMNS                   187
#define IDS_FIELD_FONT_SIZE                 188
#define IDS_FIELD_OUTPUT_NAME               189
#define IDS_REASON_ZERO_OR_MORE_REAL        190
#define IDS_REASON_POSITIVE_INTEGER         191
#define IDS_REASON_POSITIVE_REAL            192
#define IDS_REASON_NON_EMPTY_STRING         193

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
